"""Write sample ledger rows so a fresh clone has something to look at.

The track record page reads real runs, so a clone with no history shows an
empty state. That is correct behaviour but a poor first impression, and it
makes the feature hard to evaluate without spending API credits first.

Every row this writes is marked ``"sample": true`` and its note text says so
in the first line. Nothing here is a real research output, and the rows are
deliberately obvious about it — an invented track record presented as genuine
is exactly the failure the rest of this project is built to prevent.

Usage:
    python scripts/seed_demo_data.py          # append sample rows
    python scripts/seed_demo_data.py --clear  # remove them again
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "data" / "sessions" / "runs.jsonl"
NOTES = ROOT / "data" / "notes"

# Tickers drawn from the mock account and watchlist so the sample lines up
# with what get_portfolio_snapshot returns. Prices are illustrative.
SAMPLES = [
    # view_price values are anchored near each ticker's price at the time this
    # sample was written, so the resulting moves look like plausible outcomes
    # rather than implausible ones. Mixed deliberately: a scoreboard where
    # every call was right would be the least believable thing on the page.
    ("MSFT", "bullish", 441.20, 61, ["Azure growth falling below 20% for two consecutive quarters"]),
    ("AAPL", "neutral", 322.60, 45, ["Services margin compressing below 70%"]),
    ("NKE", "bearish", 47.10, 38, ["Inventory back to normal levels with gross margin recovering"]),
    ("JNJ", "bullish", 240.80, 30, ["A litigation charge materially above the reserved amount"]),
    ("PLTR", "bearish", 148.30, 22, ["Government revenue concentration falling below 40%"]),
    ("COST", "neutral", 915.40, 14, ["Membership fee growth slowing below 8%"]),
    ("XOM", "bullish", 158.90, 11, ["Sustained crude below $60 with buybacks paused"]),
]

NOTE_TEMPLATE = """> SAMPLE DATA — generated by scripts/seed_demo_data.py, not a real
> research run. Delete with `python scripts/seed_demo_data.py --clear`.

## {ticker} — Research Note (sample)

**Snapshot**
Illustrative row so the track record page has content on a fresh clone.

**View**
{rating} at ${price:.2f}.

**What would change my mind**
- {condition}
"""


def sample_rows() -> list[dict]:
    now = datetime.now(timezone.utc)
    rows = []
    for i, (ticker, rating, price, days_ago, conditions) in enumerate(SAMPLES):
        stamped = now - timedelta(days=days_ago)
        run_id = f"sample-{i:02d}-{ticker.lower()}"
        rows.append(
            {
                "run_id": run_id,
                "question": f"Sample research note on {ticker}.",
                "tool_calls": [],
                "citations": [],
                "note_path": f"../notes/{run_id}.md",
                "timestamp": stamped.isoformat(timespec="seconds").replace("+00:00", "Z"),
                "sample": True,
                "view": {
                    "rating": rating,
                    "tickers": [ticker],
                    "view_price": {ticker: price},
                    "change_my_mind": conditions,
                },
            }
        )
    return rows


def read_ledger() -> list[dict]:
    if not LEDGER.exists():
        return []
    with open(LEDGER, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def write_ledger(rows: list[dict]) -> None:
    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with open(LEDGER, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")


def seed() -> None:
    existing = read_ledger()
    if any(r.get("sample") for r in existing):
        print("Sample rows are already present. Run with --clear first to reseed.")
        return

    rows = sample_rows()
    NOTES.mkdir(parents=True, exist_ok=True)
    for row in rows:
        view = row["view"]
        ticker = view["tickers"][0]
        (NOTES / f"{row['run_id']}.md").write_text(
            NOTE_TEMPLATE.format(
                ticker=ticker,
                rating=view["rating"].capitalize(),
                price=view["view_price"][ticker],
                condition=view["change_my_mind"][0],
            ),
            encoding="utf-8",
        )

    # Appending keeps the ledger's append-only discipline intact.
    with open(LEDGER, "a", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")

    print(f"Added {len(rows)} sample views and notes.")
    print("Open the web UI and click 'Track record' to see them.")
    print("Remove with: python scripts/seed_demo_data.py --clear")


def clear() -> None:
    rows = read_ledger()
    keep = [r for r in rows if not r.get("sample")]
    removed = len(rows) - len(keep)
    if not removed:
        print("No sample rows found.")
        return

    # Rewriting is acceptable only here: this command exists to undo a
    # deliberate local seed, and it never touches a genuine run.
    write_ledger(keep)
    for note in NOTES.glob("sample-*.md"):
        note.unlink()
    print(f"Removed {removed} sample views and their notes.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clear", action="store_true", help="remove sample rows")
    args = parser.parse_args()
    clear() if args.clear else seed()
    return 0


if __name__ == "__main__":
    sys.exit(main())
